### ISSUE TITLE
AttributeError: 'InstalledAppFlow' object has no attribute 'run_console'

### ISSUE THREAD

**Issue by xaionaro** [nang149/youtubeviewcounter#4]
Hello. I tried to follow the instruction to get the viewer count, but I get this error:
```
(venv) smartoffice@alien:~/src/youtubeviewcounter$ python3 ./yt_view_counter.py
Traceback (most recent call last):
  File "/home/smartoffice/src/youtubeviewcounter/./yt_view_counter.py", line 82, in <module>
    main()
  File "/home/smartoffice/src/youtubeviewcounter/./yt_view_counter.py", line 25, in main
    credentials = flow.run_console()
AttributeError: 'InstalledAppFlow' object has no attribute 'run_console'
```
Do I do something wrong?

**Comment by xaionaro** [comment]
Found a workaround: it requires to downgrade the dependencies to:
```
google-api-python-client==1.7.2
google-auth==1.8.0
google-auth-httplib2==0.0.3
google-auth-oauthlib==0.4.1
```
Copied from https://stackoverflow.com/questions/75602866/google-oauth-attributeerror-installedappflow-object-has-no-attribute-run-co
